version: '3'
services:
    web:
        image: nginx:${NGINX_VERSION}
        container_name: nginx
        ports:
            - "80:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        volumes:
            - "./nginx/config/default.conf:/etc/nginx/conf.d/default.conf"
            - "./nginx/config/site.conf:/etc/nginx/conf.d/site.conf"
            - "./nginx/config/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./nginx/config/default.template.conf:/etc/nginx/conf.d/default.template"
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
        env_file:
            - ".env"
    php:
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build: ./php
        container_name: php
        restart: always
        volumes:
            - "./php/config/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
        ports:
            - "9000"
        env_file:
            - ".env"
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/resources:/resources
            - ./mysql/config/:/etc/mysql/conf.d
    backup:
        container_name: mysqlbackups
        image: fradelg/mysql-cron-backup
        depends_on:
            - mysqldb
        volumes:
            - ./mysql/backup:/backup
        environment:
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_USER=${MYSQL_ROOT_USER}
            - MYSQL_PASS=${MYSQL_ROOT_PASSWORD}
            - MAX_BACKUPS=5
            - INIT_BACKUP=1
            - CRON_TIME=0 */8 * * *
            - TZ=Europe/Warsaw
        restart: unless-stopped
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8081:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb